version: "3.8"
services:
  react-app:
    container_name: react-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app           # Mount the local directory to /app in the container
      - /app/node_modules  # Keep node_modules inside the container
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true # Enable file watching in Docker
